version: '3.5'
services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    command: php-fpm
    ports:
        - "9000:9000"
  nginx:
    command: nginx -g "daemon off;"
    container_name: schedule_service
    image: nginx:latest
    ports:
        - "6000:3000"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

networks:
  default:
    external:
      name: schoolar-network
