version: '3.5'
services:
  app:
    container_name: schedule
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    command: ["pipenv", "run", "gunicorn", "--bind", "0.0.0.0:3000", "--workers", "3", "wsgi:server"]
    ports:
      - "6000:3000"

networks:
  default:
    external:
      name: schoolar-network

