version: '3.5'
services:
  schedule-service:
    container_name: schedule_service
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: .
    command: "/usr/bin/supervisord"
    ports:
        - "6000:3000"

networks:
  default:
    external:
      name: schoolar-network
