"""empty message

Revision ID: 3c177e78b6d2
Revises: 
Create Date: 2019-04-02 09:04:18.186510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c177e78b6d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_path', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('is_full_day', sa.Boolean(), nullable=True),
    sa.Column('is_notifiable', sa.Boolean(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('courses')
    op.drop_table('subjects')
    op.drop_table('groups')
    op.drop_table('faculties')
    # ### end Alembic commands ###
